name: error_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  fluttertoast: ^8.2.1
  http: ^0.13.5
  jwt_decode: ^0.3.1
  riverpod_annotation: ^2.0.0
  riverpod_generator: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  hooks_riverpod: ^2.3.2
  intl: ^0.18.0
  flutter_hooks: ^0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
